# Generated by Django 5.2 on 2025-10-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('2months', '2 Months'), ('3months', '3 Months'), ('6months', '6 Months'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
