# Generated by Django 5.2 on 2025-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('chat_id', models.AutoField(help_text='Unique chat session ID (auto-increment)', primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('conversation', models.JSONField(help_text='List of messages in this chat session')),
                ('is_authenticated', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
