# Generated by Django 5.2 on 2025-12-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('action_name', models.CharField(help_text='Detected action name (e.g., update_profile, delete_account)', max_length=100)),
                ('user_prompt', models.TextField(help_text='Original user input that triggered this action')),
                ('action_payload', models.JSONField(help_text='Structured parameters extracted for the action')),
                ('action_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if action execution fails', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('executed_by', models.CharField(default='ai', help_text='Who executed the action (ai / user / system)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
