# Generated by Django 5.2 on 2025-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibot', '0003_delete_aiactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('action_id', models.AutoField(help_text='Unique action execution ID', primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action_payload', models.JSONField(help_text='Action execution payload including input, intent, and result')),
                ('is_success', models.BooleanField(help_text='True if action executed successfully')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
