# Generated by Django 5.2 on 2025-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibot', '0005_delete_aiactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('action_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Chat session ID (same as AIConversation.chat_id)')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('actions', models.JSONField(default=list, help_text='List of action executions for this chat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_action_logs',
                'ordering': ['-updated_at'],
                'unique_together': {('chat_id', 'user_id')},
            },
        ),
    ]
