# Generated by Django 5.2 on 2025-12-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibot', '0006_aiactionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIActionLog',
        ),
    ]
